# Generated by Django 2.2.6 on 2019-11-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='som',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=15)),
                ('seller', models.CharField(max_length=15)),
                ('amount', models.IntegerField(verbose_name=10000)),
                ('status', models.BooleanField(default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.stocks')),
            ],
        ),
    ]
