# Generated by Django 2.2.6 on 2019-11-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20191120_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='stock',
            field=models.CharField(max_length=23),
        ),
    ]
